---
name: MooseX-GlobRef-Object
version: 0.05
author:
  - 'Piotr Roszatycki <dexter@cpan.org>'
abstract: Store a Moose object in glob reference
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=MooseX-GlobRef-Object
  license: http://dev.perl.org/licenses/
  repository: http://code2.0beta.co.uk/moose/svn/MooseX-GlobRef-Object
requires:
  Moose: 0.56
  parent: 0
  perl: 5.006
build_requires:
  Test::Assert: 0
  Test::Unit::Lite: 0.11
provides:
  MooseX::GlobRef::Meta::Class:
    file: lib/MooseX/GlobRef/Meta/Class.pm
    version: 0.05
  MooseX::GlobRef::Meta::Instance:
    file: lib/MooseX/GlobRef/Meta/Instance.pm
    version: 0.05
  MooseX::GlobRef::Object:
    file: lib/MooseX/GlobRef/Object.pm
    version: 0.05
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
